/**
 * @file camera_agent.c
 * @brief Implementation of Standalone Camera Agent Daemon Core Pipeline.
 */

#include "camera_agent.h"
#include "hal/hal.h"
#include "json_parser.h"
#include "livestream_session_controller.h"
#include "media_frame.h"
#include "media_pipeline.h"
#include "rtp_packetizer.h"
#include "signaling_client.h"
#include "webrtc_transport.h"
#include "ws_transport.h"

#include <pthread.h>
#include <stdatomic.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

struct camera_agent {
    camera_agent_config_t config;
    hal_video_stream_t stream_handle;
    media_pipeline_t *pipeline;
    rtp_packetizer_t *packetizer;
    webrtc_transport_t *transport;
    signaling_client_t *sig_client;
    ws_transport_ctx_t *ws_ctx;
    livestream_session_controller_t *controller;

    pthread_t capture_thread;
    atomic_bool is_running;
};

/**
 * @brief Callback function invoked when raw RTP packets are generated by the rtp_packetizer.
 * 
 * Transmits the formatted RTP packet over WebRTC transport via DTLS-SRTP.
 * 
 * @param[in] packet_data Pointer to raw RTP packet bytes. Must not be NULL.
 * @param[in] packet_size Size of packet in bytes. Must be > 12.
 * @param[in] user_data Opaque pointer to camera_agent_t instance.
 */
static void on_rtp_packet_generated(const uint8_t *packet_data, size_t packet_size, void *user_data) {
    camera_agent_t *agent = (camera_agent_t *)user_data;
    if (agent && agent->transport) {
        webrtc_transport_send_rtp(agent->transport, packet_data, packet_size);
    }
}

/**
 * @brief Callback function invoked when signaling messages are received from the WS server.
 * 
 * Parses incoming JSON envelope and forwards payload to livestream_session_controller.
 * 
 * @param[in] type Message type string ("OFFER", "ANSWER", "CANDIDATE", etc.).
 * @param[in] session_id Session ID string matching session.
 * @param[in] payload_json Stringified JSON payload object.
 * @param[in] user_data Opaque pointer to camera_agent_t instance.
 */
static void on_signaling_message_received(const char *type, const char *session_id, const char *payload_json, void *user_data) {
    camera_agent_t *agent = (camera_agent_t *)user_data;
    if (agent && agent->controller) {
        if (strcmp(type, "ANSWER") == 0) {
            livestream_session_controller_apply_answer(agent->controller, payload_json);
        } else if (strcmp(type, "CANDIDATE") == 0) {
            livestream_session_controller_add_ice_candidate(agent->controller, payload_json, "video");
        }
    }
}

/**
 * @brief Background worker thread performing HAL camera frame acquisition.
 * 
 * Polls HAL camera device for encoded video frames and pushes them into the zero-copy media pipeline.
 * 
 * @param[in] arg Pointer to camera_agent_t instance.
 * @return NULL upon thread termination.
 */
static void *capture_worker_thread(void *arg) {
    camera_agent_t *agent = (camera_agent_t *)arg;
    if (!agent) return NULL;

    printf("[CameraAgent] Capture worker thread started.\n");

    while (atomic_load(&agent->is_running)) {
        hal_video_frame_t hal_frame;
        memset(&hal_frame, 0, sizeof(hal_frame));

        hal_status_t status = hal_read_video_frame(agent->stream_handle, 100, &hal_frame);
        if (status == HAL_OK) {
            uint64_t pts_us = hal_frame.capture_timestamp.value_ns / 1000ULL;

            /* Simulated H.264 NALU payload for daemon testing */
            uint8_t mock_nalu[] = {0x00, 0x00, 0x00, 0x01, 0x65, 0x88, 0x84, 0x00};
            media_buffer_t *buf = media_buffer_create(sizeof(mock_nalu));
            if (buf) {
                memcpy(buf->data, mock_nalu, sizeof(mock_nalu));
                buf->size = sizeof(mock_nalu);

                media_frame_t frame = {
                    .buffer = buf,
                    .data = buf->data,
                    .size = buf->size,
                    .timestamp = {
                        .pts_us = pts_us,
                        .capture_time_us = pts_us,
                        .sequence = hal_frame.sequence
                    },
                    .codec = MEDIA_CODEC_H264,
                    .frame_type = MEDIA_FRAME_TYPE_IDR,
                    .flags = 0
                };

                if (agent->pipeline) {
                    media_pipeline_push_frame(agent->pipeline, &frame);
                }
                if (agent->packetizer) {
                    rtp_packetizer_push_frame(agent->packetizer, &frame);
                }

                media_buffer_release(buf);
            }
        } else {
            usleep(10000); /* 10ms sleep if no frame available */
        }
    }

    printf("[CameraAgent] Capture worker thread exiting.\n");
    return NULL;
}

int camera_agent_create(const camera_agent_config_t *config, camera_agent_t **out_agent) {
    if (!config || !out_agent || !config->signaling_server_uri || !config->session_id) {
        return -1;
    }

    camera_agent_t *agent = (camera_agent_t *)calloc(1, sizeof(camera_agent_t));
    if (!agent) {
        return -2;
    }

    agent->config = *config;
    atomic_init(&agent->is_running, false);

    /* 1. Initialize HAL Video Input Mode and Stream */
    hal_video_mode_t mode = {
        .width = config->width ? config->width : 1920,
        .height = config->height ? config->height : 1080,
        .frame_rate = { .numerator = config->fps ? config->fps : 30, .denominator = 1 },
        .format = HAL_PIXEL_FORMAT_NV12
    };

    if (hal_open_video_stream((hal_video_input_id_t)config->camera_device_id, &mode, &agent->stream_handle) != HAL_OK) {
        printf("[CameraAgent] Warning: hal_open_video_stream fallback.\n");
    }

    /* 2. Initialize Zero-Copy Media Pipeline */
    media_pipeline_config_t pipe_cfg = {
        .max_queue_depth = 32,
        .drop_oldest_on_overflow = true
    };
    if (media_pipeline_create(&pipe_cfg, &agent->pipeline) != 0) {
        hal_close_video_stream(agent->stream_handle);
        free(agent);
        return -2;
    }

    /* 3. Initialize H.264 RTP Packetizer */
    rtp_packetizer_config_t rtp_cfg = {
        .ssrc = config->ssrc ? config->ssrc : 0x12345678,
        .payload_type = 96,
        .mtu = 1200
    };
    if (rtp_packetizer_create(&rtp_cfg, on_rtp_packet_generated, agent, &agent->packetizer) != 0) {
        media_pipeline_destroy(agent->pipeline);
        hal_close_video_stream(agent->stream_handle);
        free(agent);
        return -2;
    }

    /* 4. Initialize WebRTC Transport */
    webrtc_transport_callbacks_t transport_cbs = {
        .on_local_description = NULL,
        .on_local_candidate = NULL,
        .on_state_changed = NULL
    };
    webrtc_transport_config_t transport_cfg = {
        .stun_server = "stun:stun.l.google.com:19302",
        .enable_libdatachannel = config->enable_libdatachannel
    };
    if (webrtc_transport_create(&transport_cfg, &transport_cbs, agent, &agent->transport) != 0) {
        rtp_packetizer_destroy(agent->packetizer);
        media_pipeline_destroy(agent->pipeline);
        hal_close_video_stream(agent->stream_handle);
        free(agent);
        return -4;
    }

    /* 5. Initialize POSIX WS Transport & Signaling Client */
    if (ws_transport_create(config->signaling_server_uri, &agent->ws_ctx) != 0) {
        webrtc_transport_destroy(agent->transport);
        rtp_packetizer_destroy(agent->packetizer);
        media_pipeline_destroy(agent->pipeline);
        hal_close_video_stream(agent->stream_handle);
        free(agent);
        return -4;
    }

    signaling_client_config_t sig_cfg = {
        .transport_ops = ws_transport_get_ops(),
        .transport_ctx = agent->ws_ctx,
        .server_uri = config->signaling_server_uri
    };
    if (signaling_client_create(&sig_cfg, on_signaling_message_received, agent, &agent->sig_client) != 0) {
        ws_transport_destroy(agent->ws_ctx);
        webrtc_transport_destroy(agent->transport);
        rtp_packetizer_destroy(agent->packetizer);
        media_pipeline_destroy(agent->pipeline);
        hal_close_video_stream(agent->stream_handle);
        free(agent);
        return -4;
    }

    /* 6. Initialize Livestream Session Controller */
    livestream_session_config_t controller_cfg = {
        .session_id = config->session_id,
        .media_pipeline = agent->pipeline,
        .transport_config = transport_cfg
    };
    if (livestream_session_controller_create(&controller_cfg, &transport_cbs, agent, &agent->controller) != 0) {
        signaling_client_destroy(agent->sig_client);
        ws_transport_destroy(agent->ws_ctx);
        webrtc_transport_destroy(agent->transport);
        rtp_packetizer_destroy(agent->packetizer);
        media_pipeline_destroy(agent->pipeline);
        hal_close_video_stream(agent->stream_handle);
        free(agent);
        return -4;
    }

    *out_agent = agent;
    printf("[CameraAgent] Camera Agent created successfully.\n");
    return 0;
}

int camera_agent_start(camera_agent_t *agent) {
    if (!agent) return -1;
    if (atomic_load(&agent->is_running)) return -2;

    atomic_store(&agent->is_running, true);

    /* Start HAL video stream */
    hal_start_video_stream(agent->stream_handle);

    /* Connect signaling client to WS server */
    if (signaling_client_connect(agent->sig_client) != 0) {
        printf("[CameraAgent] Warning: WS signaling connect deferred or non-blocking.\n");
    }

    /* Spawn capture worker thread */
    if (pthread_create(&agent->capture_thread, NULL, capture_worker_thread, agent) != 0) {
        hal_stop_video_stream(agent->stream_handle);
        atomic_store(&agent->is_running, false);
        return -4;
    }

    printf("[CameraAgent] Camera Agent daemon started successfully.\n");
    return 0;
}

int camera_agent_stop(camera_agent_t *agent) {
    if (!agent) return -1;
    if (!atomic_load(&agent->is_running)) return 0;

    atomic_store(&agent->is_running, false);

    /* Stop HAL camera stream and join worker thread */
    hal_stop_video_stream(agent->stream_handle);
    pthread_join(agent->capture_thread, NULL);

    /* Stop session controller */
    if (agent->controller) {
        livestream_session_controller_stop(agent->controller);
    }

    printf("[CameraAgent] Camera Agent daemon stopped successfully.\n");
    return 0;
}

void camera_agent_destroy(camera_agent_t *agent) {
    if (!agent) return;

    camera_agent_stop(agent);

    if (agent->controller) {
        livestream_session_controller_destroy(agent->controller);
        agent->controller = NULL;
    }
    if (agent->sig_client) {
        signaling_client_destroy(agent->sig_client);
        agent->sig_client = NULL;
    }
    if (agent->ws_ctx) {
        ws_transport_destroy(agent->ws_ctx);
        agent->ws_ctx = NULL;
    }
    if (agent->transport) {
        webrtc_transport_destroy(agent->transport);
        agent->transport = NULL;
    }
    if (agent->packetizer) {
        rtp_packetizer_destroy(agent->packetizer);
        agent->packetizer = NULL;
    }
    if (agent->pipeline) {
        media_pipeline_destroy(agent->pipeline);
        agent->pipeline = NULL;
    }

    hal_close_video_stream(agent->stream_handle);

    free(agent);
    printf("[CameraAgent] Camera Agent destroyed successfully.\n");
}
